/* DO NOT EDIT THIS FILE - it is machine generated */
#ifndef _Included_com_sentinel_v2x_bridge_SecurityEngine
#define _Included_com_sentinel_v2x_bridge_SecurityEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sentinel_v2x_bridge_SecurityEngine
 * Method:    verifyPacket
 * Signature: ([B[B[[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sentinel_v2x_bridge_SecurityEngine_verifyPacket
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jobjectArray);

/*
 * Class:     com_sentinel_v2x_bridge_SecurityEngine
 * Method:    extractSenderInfo
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sentinel_v2x_bridge_SecurityEngine_extractSenderInfo
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_sentinel_v2x_bridge_SecurityEngine
 * Method:    initializeWithRootCA
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_sentinel_v2x_bridge_SecurityEngine_initializeWithRootCA
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_sentinel_v2x_bridge_SecurityEngine
 * Method:    validateCertificateChain
 * Signature: ([[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sentinel_v2x_bridge_SecurityEngine_validateCertificateChain
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_sentinel_v2x_bridge_SecurityEngine
 * Method:    parseIEEE1609Message
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sentinel_v2x_bridge_SecurityEngine_parseIEEE1609Message
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_sentinel_v2x_bridge_SecurityEngine
 * Method:    cleanup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sentinel_v2x_bridge_SecurityEngine_cleanup
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
